import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  webOuterWrapper: { flex: 1, backgroundColor: '#0F172A', width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center' },
  phoneContainer: { flex: 1, backgroundColor: '#F3F4F6', width: '100%', maxWidth: 390, height: '100%', maxHeight: 760, overflow: 'hidden', position: 'relative', marginTop: 45, borderRadius: 12 },

  loginWrapper: { flex: 1, backgroundColor: '#0B0F19', justifyContent: 'center', alignItems: 'center', padding: 24 },
  loginCenterCard: { width: '100%', alignItems: 'center' },
  loginLogo: { fontSize: 36, fontWeight: '900', color: '#FFFFFF', letterSpacing: 4, marginBottom: 4 },
  loginSubText: { fontSize: 8, color: '#9CA3AF', fontWeight: '700', marginBottom: 32 },
  inputGroup: { width: '100%', marginBottom: 16 },
  inputLabel: { fontSize: 10, fontWeight: '700', color: '#9CA3AF', marginBottom: 6 },
  loginInput: { backgroundColor: '#1F2937', borderRadius: 8, height: 44, paddingHorizontal: 14, color: '#FFFFFF', fontSize: 13 },
  loginButton: { width: '100%', backgroundColor: '#FFFFFF', borderRadius: 8, height: 44, justifyContent: 'center', alignItems: 'center', marginTop: 14 },
  loginButtonText: { color: '#0B0F19', fontWeight: '900' },

  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 12, height: 52, backgroundColor: '#0B0F19', zIndex: 9999 },
  clickableArea: { padding: 10 },
  headerIcon: { fontSize: 16, color: '#FFF' },
  headerTitle: { fontSize: 16, fontWeight: '900', color: '#FFF', letterSpacing: 2 },
  profileButton: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center' },
  profileText: { color: '#0B0F19', fontWeight: '900', fontSize: 12 },

  scrollArea: { flex: 1, padding: 12, marginBottom: 54 },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: '#0B0F19', marginBottom: 10, marginTop: 4 },
  sectionTitleLarge: { fontSize: 16, fontWeight: '800', color: '#0B0F19' },

  formCard: { backgroundColor: '#FFF', padding: 16, borderRadius: 12, borderWidth: 0.5, borderColor: '#E5E7EB' },
  formLabel: { fontSize: 11, fontWeight: '700', color: '#374151', marginBottom: 6 },
  formInput: { backgroundColor: '#F9FAFB', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, height: 40, paddingHorizontal: 12, fontSize: 12, marginBottom: 14, color: '#111827' },
  submitFormBtn: { backgroundColor: '#0B0F19', height: 42, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  submitFormBtnText: { color: '#FFF', fontWeight: '800' },

  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  statBox: { width: '31%', backgroundColor: '#FFF', borderRadius: 12, padding: 10, marginBottom: 10, alignItems: 'center', height: 75, justifyContent: 'center', borderWidth: 0.5, borderColor: '#E5E7EB' },
  statNum: { fontSize: 15, fontWeight: '900', color: '#0B0F19' },
  statSub: { fontSize: 8, color: '#9CA3AF', fontWeight: '600' },
  statLabel: { fontSize: 8, color: '#374151', textAlign: 'center', fontWeight: '700', marginTop: 2 },

  chartMockup: { flexDirection: 'row', height: 90, backgroundColor: '#E0DBFA', borderRadius: 12, alignItems: 'flex-end', justifyContent: 'space-around', padding: 12, marginTop: 6 },
  chartBar: { width: 14, backgroundColor: '#5B21B6', borderRadius: 4 },
  chartLabelText: { fontSize: 8, color: '#6B7280', fontWeight: '600' },

  categoryRowCard: { flexDirection: 'row', backgroundColor: '#FFF', padding: 12, borderRadius: 10, alignItems: 'center', marginBottom: 8 },
  categoryIconWrapper: { width: 36, height: 36, borderRadius: 6, backgroundColor: '#EEF2F6', justifyContent: 'center', alignItems: 'center' },
  categoryNameText: { fontSize: 13, fontWeight: '700' },
  categoryCountText: { fontSize: 10, color: '#6B7280' },
  actionInlineBtn: { backgroundColor: '#0B0F19', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6 },
  actionBtnText: { color: '#FFF', fontSize: 10, fontWeight: '700' },
  productCardLarge: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 14, padding: 12, marginBottom: 10, alignItems: 'center' },
  productImageLarge: { width: 60, height: 60, borderRadius: 10 },
  productInfoLarge: { flex: 1, paddingLeft: 12 },
  productNameTextLarge: { fontSize: 13, fontWeight: '800' },
  productMetaTextLarge: { fontSize: 10, color: '#6B7280' },
  priceTagLarge: { fontSize: 13, fontWeight: '900' },

  detailCard: { backgroundColor: '#FFF', width: '100%', borderRadius: 12, padding: 16 },
  detailImage: { width: '100%', height: 180, borderRadius: 8, marginBottom: 12 },
  detailTitle: { fontSize: 16, fontWeight: '900', color: '#0B0F19', marginBottom: 14 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 0.5, borderBottomColor: '#F3F4F6' },
  detailSectionLabel: { fontSize: 12, fontWeight: '700', color: '#6B7280' },
  detailValueText: { fontSize: 12, fontWeight: '800', color: '#0B0F19' },

  qrCodeWrapper: { alignItems: 'center', marginTop: 20, paddingTop: 16, borderTopWidth: 1, borderTopColor: '#E5E7EB', borderStyle: 'dashed' },
  qrLabel: { fontSize: 12, fontWeight: '800', color: '#374151', marginBottom: 8 },
  qrImageMock: { width: 110, height: 110, backgroundColor: '#F3F4F6', padding: 6, borderRadius: 6 },
  qrSubText: { fontSize: 9, color: '#9CA3AF', marginTop: 6, fontWeight: '600' },

  fixedBottomTabContainer: { flexDirection: 'row', backgroundColor: '#0B0F19', height: 54, width: '100%', position: 'absolute', bottom: 0, left: 0, right: 0, borderTopWidth: 1, borderColor: '#1F2937', zIndex: 9999 },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabIcon: { fontSize: 13, color: '#6B7280' },
  tabLabel: { fontSize: 8, color: '#6B7280', marginTop: 2 },
  tabActive: { color: '#FFF' },

  menuOverlayContainer: { flex: 1, backgroundColor: '#0B0F19', padding: 24 },
  menuHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 40 },
  closeMenuText: { fontSize: 22, color: '#FFF' },
  menuLogo: { fontSize: 20, fontWeight: '900', color: '#FFF' },
  menuLinksContainer: { flex: 1 },
  menuLinkItem: { paddingVertical: 16 },
  menuLinkLabel: { fontSize: 14, color: '#FFF' },
  menuLogoutButton: { paddingVertical: 16, alignItems: 'center' },
  menuLogoutText: { color: '#EF4444', fontWeight: '700' },
});