import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  webOuterWrapper: { flex: 1, backgroundColor: '#101B30', width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center' },
  phoneContainer: { flex: 1, backgroundColor: '#F5F7FB', width: '100%', maxWidth: 430, height: '100%', maxHeight: 860, overflow: 'hidden', position: 'relative', borderRadius: 24, shadowColor: '#020817', shadowOpacity: 0.28, shadowRadius: 28, elevation: 12 },
  loginWrapper: { flex: 1, backgroundColor: '#16233D', justifyContent: 'center', padding: 26 }, loginCenterCard: { width: '100%' }, loginLogo: { fontSize: 40, fontWeight: '900', color: '#FFFFFF', letterSpacing: 5, textAlign: 'center' }, loginSubText: { fontSize: 10, color: '#B7C5DD', fontWeight: '700', letterSpacing: 1.3, textAlign: 'center', marginTop: 7, marginBottom: 36 },
  inputGroup: { width: '100%', marginBottom: 15 }, inputLabel: { fontSize: 11, fontWeight: '800', color: '#D7E1F3', marginBottom: 7 }, loginInput: { backgroundColor: '#223553', borderWidth: 1, borderColor: '#365174', borderRadius: 14, height: 50, paddingHorizontal: 15, color: '#FFFFFF', fontSize: 14 }, loginButton: { width: '100%', backgroundColor: '#E8B44F', borderRadius: 14, height: 50, justifyContent: 'center', alignItems: 'center', marginTop: 10, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 8, elevation: 3 }, loginButtonText: { color: '#17233B', fontWeight: '900', fontSize: 14 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 14, height: 64, backgroundColor: '#192A46', zIndex: 10 }, headerButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#2A3F61', justifyContent: 'center', alignItems: 'center' }, headerBrand: { alignItems: 'center' }, headerTitle: { fontSize: 17, fontWeight: '900', color: '#FFFFFF', letterSpacing: 3 }, headerSubtitle: { color: '#9EB3D1', fontSize: 8, fontWeight: '800', letterSpacing: 2, marginTop: 1 }, profileButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#E8B44F', justifyContent: 'center', alignItems: 'center' },
  scrollArea: { flex: 1, paddingHorizontal: 16, paddingTop: 18, marginBottom: 68 }, sectionTitle: { fontSize: 13, fontWeight: '800', color: '#7A89A0', letterSpacing: 0.5, marginBottom: 10 }, sectionTitleLarge: { fontSize: 24, fontWeight: '900', color: '#192A46', letterSpacing: -0.4 }, sectionSubtitle: { fontSize: 12, color: '#75839A', marginTop: 4, lineHeight: 18 },
  formCard: { backgroundColor: '#FFFFFF', padding: 18, borderRadius: 18, borderWidth: 1, borderColor: '#E7ECF3', shadowColor: '#20324A', shadowOpacity: 0.05, shadowRadius: 12, elevation: 2, marginTop: 14 }, formLabel: { fontSize: 11, fontWeight: '800', color: '#40516A', marginBottom: 7 }, formInput: { backgroundColor: '#F7F9FC', borderWidth: 1, borderColor: '#E1E7F0', borderRadius: 12, height: 46, paddingHorizontal: 13, fontSize: 13, marginBottom: 14, color: '#192A46' }, submitFormBtn: { backgroundColor: '#192A46', height: 48, borderRadius: 13, justifyContent: 'center', alignItems: 'center' }, submitFormBtnText: { color: '#FFFFFF', fontWeight: '900', fontSize: 13 },
  heroCard: { backgroundColor: '#192A46', borderRadius: 24, padding: 22, marginBottom: 22, minHeight: 164, justifyContent: 'center', overflow: 'hidden', shadowColor: '#10203A', shadowOpacity: 0.16, shadowRadius: 16, elevation: 4 }, heroEyebrow: { color: '#F4C968', fontSize: 10, letterSpacing: 1.5, fontWeight: '900', marginBottom: 10 }, heroTitle: { color: '#FFFFFF', fontSize: 27, fontWeight: '800', letterSpacing: -0.7, lineHeight: 33, maxWidth: '86%' }, heroCopy: { color: '#C7D3E5', fontSize: 12, marginTop: 9, lineHeight: 18, maxWidth: '84%' }, heroAccent: { position: 'absolute', width: 118, height: 118, borderRadius: 59, backgroundColor: '#2B456B', right: -46, bottom: -52 }, heroAccentTop: { position: 'absolute', width: 60, height: 60, borderRadius: 30, backgroundColor: '#223A5D', right: 30, top: -30 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, statBox: { width: '48.5%', backgroundColor: '#FFFFFF', borderRadius: 18, padding: 15, marginBottom: 12, borderWidth: 1, borderColor: '#E7ECF3', minHeight: 102, justifyContent: 'center' }, statHighlight: { backgroundColor: '#FFF7E6', borderColor: '#F4D89B' }, statNum: { fontSize: 25, fontWeight: '900', color: '#192A46' }, statSub: { fontSize: 10, color: '#78879D', fontWeight: '700', marginTop: 4 }, statLabel: { fontSize: 10, color: '#4E5E76', fontWeight: '900', letterSpacing: 0.6, marginTop: 5 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 11 }, textButton: { color: '#B77B09', fontSize: 12, fontWeight: '900' },
  categoryRowCard: { flexDirection: 'row', backgroundColor: '#FFFFFF', padding: 13, borderRadius: 16, alignItems: 'center', marginBottom: 9, borderWidth: 1, borderColor: '#E7ECF3' }, categoryIconWrapper: { width: 42, height: 42, borderRadius: 13, backgroundColor: '#EEF3FA', justifyContent: 'center', alignItems: 'center' }, categoryNameText: { fontSize: 13, fontWeight: '800', color: '#243550' }, categoryCountText: { fontSize: 11, color: '#7B899E', marginTop: 3 }, actionInlineBtn: { backgroundColor: '#192A46', paddingHorizontal: 13, height: 35, justifyContent: 'center', borderRadius: 10 }, actionBtnText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  searchContainer: { position: 'relative', marginTop: 16, marginBottom: 11 }, searchIcon: { position: 'absolute', left: 14, top: 13, zIndex: 1 }, searchInput: { paddingLeft: 43, marginBottom: 0, backgroundColor: '#FFFFFF' }, productsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, productCardLarge: { width: '48.5%', backgroundColor: '#FFFFFF', borderRadius: 18, padding: 10, marginBottom: 12, borderWidth: 1, borderColor: '#E7ECF3', shadowColor: '#20324A', shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 }, productImageWrap: { position: 'relative' }, productImageLarge: { width: '100%', height: 142, borderRadius: 14, backgroundColor: '#EEF3FA' }, productInfoLarge: { paddingTop: 10 }, productNameTextLarge: { fontSize: 13, fontWeight: '900', color: '#243550' }, productMetaTextLarge: { fontSize: 10, color: '#77869A', marginTop: 3 }, productStockRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 7 }, priceTagLarge: { fontSize: 14, fontWeight: '900', color: '#B77B09' }, productStockBadge: { borderRadius: 8, paddingHorizontal: 6, paddingVertical: 4 }, productStockBadgeLow: { backgroundColor: '#FDE9E7' }, productStockBadgeOk: { backgroundColor: '#E4F3E7' }, productStockText: { fontSize: 8, fontWeight: '900' }, productStockTextLow: { color: '#C34C45' }, productStockTextOk: { color: '#39804D' }, favoriteButton: { position: 'absolute', top: 8, right: 8, width: 32, height: 32, borderRadius: 16, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center' },
  emptyState: { alignItems: 'center', paddingVertical: 46, paddingHorizontal: 20 }, emptyStateTitle: { color: '#31445F', fontSize: 15, fontWeight: '900', marginTop: 12 }, emptyStateCopy: { color: '#7B899E', fontSize: 12, textAlign: 'center', marginTop: 6 },
  detailCard: { backgroundColor: '#FFFFFF', width: '100%', borderRadius: 20, padding: 16, borderWidth: 1, borderColor: '#E7ECF3' }, detailImage: { width: '100%', height: 220, borderRadius: 16, marginBottom: 15 }, detailTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 }, detailTitle: { flex: 1, fontSize: 21, fontWeight: '900', color: '#192A46', marginRight: 12 }, detailPrice: { fontSize: 19, fontWeight: '900', color: '#B77B09', marginBottom: 10 }, detailRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: '#EDF0F5' }, detailSectionLabel: { fontSize: 12, fontWeight: '700', color: '#7B899E' }, detailValueText: { fontSize: 12, fontWeight: '800', color: '#243550', maxWidth: '60%', textAlign: 'right' }, dangerButton: { backgroundColor: '#FFF1F1', padding: 13, borderRadius: 13, marginTop: 10, alignItems: 'center' }, dangerButtonText: { color: '#C43E3E', fontWeight: '900' },
  fixedBottomTabContainer: { flexDirection: 'row', backgroundColor: '#192A46', height: 68, width: '100%', position: 'absolute', bottom: 0, left: 0, right: 0, paddingHorizontal: 5, paddingTop: 7, zIndex: 10 }, tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 12, gap: 3 }, tabItemActive: { backgroundColor: '#2A3F61' }, tabLabel: { fontSize: 9, color: '#AAB6C8', fontWeight: '700' }, tabActive: { color: '#FFFFFF' },
  menuOverlayContainer: { flex: 1, backgroundColor: '#192A46', padding: 24 }, menuHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 40 }, closeMenuText: { fontSize: 22, color: '#FFFFFF' }, menuLogo: { fontSize: 22, fontWeight: '900', letterSpacing: 3, color: '#FFFFFF' }, menuLinksContainer: { flex: 1 }, menuLinkItem: { paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#2B4163' }, menuLinkLabel: { fontSize: 14, color: '#FFFFFF', fontWeight: '700' }, menuLogoutButton: { backgroundColor: '#263A5A', paddingVertical: 15, alignItems: 'center', borderRadius: 13 }, menuLogoutText: { color: '#F5C4C4', fontWeight: '800' }, loginModeButton: { alignItems: 'center', marginTop: 18, paddingVertical: 8 }, loginModeText: { color: '#D7E1F3', fontSize: 12, fontWeight: '700' }, passwordToggle: { color: '#E8B44F', fontSize: 11, fontWeight: '800', marginTop: 7 }, passwordError: { color: '#FFB4AE', fontSize: 11, fontWeight: '700', marginTop: -7 },
});
